name: Build

on:
  push:
    branches: [ "main", "build-windows-exe" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-chocolatey:

    #Runs from Vagrant machine github-action-runners\build-windows-exe
    #  See instructions in Vagrantfile
    runs-on: build-windows-exe

    steps:
    - uses: actions/checkout@v3
    - name: Build Windows Exe
      run: |
        Write-Host Building Version 0.0.0-beta${{ github.run_number }}
        pyinstaller --noconfirm FloHsm.pyinstaller.spec
        .\dist\FloHsm\FloHsm.exe -h
        sed -i 's/__VERSION__/0.0.0-beta${{ github.run_number }}/g' .\Choco\flohsm.nuspec
        choco pack .\Choco\flohsm.nuspec
        Get-ChildItem flohsm.0.0.0-beta${{ github.run_number }}.nupkg
        #choco push .\flohsm.0.0.0-beta${{ github.run_number }}.nupkg --key ${{ secrets.CHOCOLATEY_API_KEY }} --source https://push.chocolatey.org/

  build-docker:

    runs-on: build-docker-image

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flohsm:latest;
    - name: Publish if on main branch
      run: |
        echo Branch: "${{github.ref}}";
        if [ "${{github.ref}}" = "refs/heads/main" ]; then
          echo main branch, so publish
          docker tag flohsm:latest tekkiesuk/flohsm:latest; 
          docker tag flohsm:latest tekkiesuk/flohsm:0.0.0-beta${{ github.run_number }}; 
          docker login -u tekkiesuk -p ${{ secrets.DOCKER_HUB_CRUD }};
          docker push tekkiesuk/flohsm:latest;
          docker push tekkiesuk/flohsm:0.0.0-beta${{ github.run_number }}; 
        else
          echo Skip publish;
        fi;
