name: Build Windows EXE
#Runs from Vagrant machine github-action-runners\build-windows-exe
#  See instructions in Vagrantfile

on:
  push:
    branches: [ "main", "build-windows-exe" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: build-windows-exe

    steps:
    - uses: actions/checkout@v3
    - name: Build Windows Exe
      run: |
        Write-Host Variables: ${{ vars.ENVIRONMENT_STAGE }} ${{ GITHUB_RUN_ID }} 0.0.0.${{ GITHUB_RUN_NUMBER }}
        pyinstaller --noconfirm FloHsm.pyinstaller.spec
        .\dist\FloHsm\FloHsm.exe -h
