name: Docker Image CI

on:
  push:
    branches: [ "master", "develop", "debug-build" ]
  pull_request:
    branches: [ "master", "develop", "debug-build" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag flohsm:latest;
        docker tag flohsm:latest tekkiesuk/flohsm:latest; 
        docker login -u tekkiesuk -p ${{ secrets.DOCKER_HUB_CRUD }};
        docker push tekkiesuk/flohsm:latest
