name: Build Windows EXE

on:
  push:
    branches: [ "main", "build-windows-exe" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    #Runs from Vagrant machine github-action-runners\build-windows-exe
    #  See instructions in Vagrantfile
    runs-on: build-windows-exe

    steps:
    - uses: actions/checkout@v3
    - name: Build Windows Exe
      run: |
        Write-Host Building Version 0.0.0-beta${{ github.run_number }}
        pyinstaller --noconfirm FloHsm.pyinstaller.spec
        .\dist\FloHsm\FloHsm.exe -h
        sed -i 's/__VERSION__/0.0.0-beta${{ github.run_number }}/g' .\Choco\flohsm.nuspec
        choco pack .\Choco\flohsm.nuspec
        Get-ChildItem flohsm.0.0.0-beta${{ github.run_number }}.nupkg

