name: Build Windows EXE

on:
  push:
    branches: [ "main", "build-windows-exe" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    #Runs from Vagrant machine github-action-runners\build-windows-exe
    #  See instructions in Vagrantfile
    runs-on: build-windows-exe

    steps:
    - uses: actions/checkout@v3
    - name: Build Windows Exe
      run: |
        Write-Host Version 0.0.0.${{ vars.GITHUB_RUN_NUMBER }} 0.0.0.${{ github.run_number }}
        pyinstaller --noconfirm FloHsm.pyinstaller.spec
        .\dist\FloHsm\FloHsm.exe -h
