name: Docker Image CI

on:
  push:
    branches: [ "master", "build" ]
  pull_request:
    branches: [ "master", "build" ]

jobs:

  build:

    runs-on: 
    - ubuntu-latest
    - self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: >
        docker build . --file Dockerfile --tag flohsm:latest
        run: docker tag flohsm:latest finiteresource/flohsm:latest
        run: docker login -u finiteresource -p ${{ secrets.DOCKER_HUB_CRUD }}
        run: docker push finiteresource/flohsm:latest

